name: Deploy Dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: 의존성 설치
        run: npm i

      - name: env 파일 생성
        run: echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env

      - name: 빌드
        run: npm run build

      - name: AWS Resource에 접근할 수 있게 AWS 인증 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: S3 기존파일 전체 삭제
        run: aws s3 rm --recursive s3://dev-whats-cooking-today

      - name: S3에 빌드 된 파일 업로드
        run: aws s3 cp ./dist s3://dev-whats-cooking-today/ --recursive

      - name: CloudFront 캐시 무효화
        run: aws cloudfront create-invalidation --distribution-id E198D3AE2YRCNV --paths '/*'
